# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!

workspace 'DIDA'
project 'DIDA'

target 'DIDA' do
  project 'DIDA'

  # Rx
    pod 'RxSwift', '~> 6.5.0'
    pod 'RxCocoa', '~> 6.5.0'
    pod 'RxDataSources', '~> 5.0.0'

  # UI
    pod 'SnapKit', '~> 5.0.0'

   # internal storage
    pod 'KeychainSwift', '~> 20.0'

  # Misc.
    pod 'Kingfisher', '~> 7.0'

    pod 'Moya', '~> 15.0'

end

target 'DIDA-UI' do
  
  # UI
    pod 'SnapKit', '~> 5.0.0'

  # Misc.
    pod 'Kingfisher', '~> 7.0'

end
