# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!

workspace 'DIDA'
project 'DIDA'

target 'DIDA' do

  # Rx
    pod 'RxSwift', '~> 6.5.0'
    pod 'RxCocoa', '~> 6.5.0'
    pod 'RxDataSources', '~> 5.0.0'
    pod 'RxKeyboard'
    pod 'RxOptional'

  # UI
    pod 'SnapKit', '~> 5.0.0'

   # internal storage
    pod 'KeychainSwift', '~> 20.0'

  # Misc.
    pod 'Kingfisher', '~> 7.0'
    pod 'Moya/RxSwift'
    pod 'lottie-ios'

  # kakao
    pod 'KakaoSDKUser'

end

target 'DIDA-UI' do
  
  # UI
    pod 'SnapKit', '~> 5.0.0'

  # Misc.
    pod 'Kingfisher', '~> 7.0'

end
